name: "ROHub Sync Action"
description: "A GitHub Action to make/sync up with a rohub resource"
inputs:
  rohub-user:
    description: "ROHub user token"
    required: true
  rohub-password:
    description: "ROHub password token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.rohub-user }}
    - ${{ inputs.rohub-password }}
